site:
  title: SUSE Security Vulnerability Scanner
  url: /
  start_page: 0.11.3@vulnerability-scanner:en:introduction.adoc

content:
  sources:
    - url: https://github.com/rancher/sbomscanner-product-docs.git
      branches: [main]
      start_paths: [versions/v*]

ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-pagination: ''
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml
    enabled: true

output:
  dir: build/site

